auth = "certificate"
ipv4-network = 192.168.101.0/24
listen-host-is-dyndns = False
tcp-port = 8443
udp-port = 8443
run-as-user = root
run-as-group = root
socket-file = /var/run/ocserv-crt.socket
occtl-socket-file = /var/run/occtl-crt.socket

server-cert = /etc/ocserv/.lego/certificates/185.20.139.137.crt
server-key = /etc/ocserv/.lego/certificates/185.20.139.137.key
ca-cert = /etc/ocserv-crt/ca/ca-cert.pem

max-clients = 240
max-same-clients = 4
keepalive = 15
dpd = 60
mobile-dpd = 7200
cookie-timeout = 604800
try-mtu-discovery = True
mtu = 1200
cert-user-oid = 2.5.4.3
# crl = /etc/ocserv/crl.pem
tls-priorities = "NORMAL:%SERVER_PRECEDENCE:%COMPAT:-VERS-SSL3.0"
#tls-priorities = "NORMAL:-VERS-SSL3.0:-VERS-TLS1.0:-VERS-TLS1.1:-VERS-TLS1.2:+VERS-TLS1.3"
auth-timeout = 240
min-reauth-time = 3
max-ban-score = 500
ban-reset-time = 300
deny-roaming = False
rekey-time = 172800
rekey-method = ssl
use-utmp = True
use-occtl = True
pid-file = /var/run/ocserv-crt.pid
device = tun-crt
predictable-ips = False
tunnel-all-dns = true
dns = 1.1.1.1
dns = 8.8.8.8
ping-leases = False
output-buffer = 0
cisco-client-compat = True
compression= False
dtls-legacy = True
# listen-host = 185.20.139.137 # disabled for dual ipv4/ipv6
route = default

# ipv6-network = 2001:db8:cafe:beef::/64
# ipv6-subnet-prefix = 128
